export const config = {
    NODE_ENV: process.env.NODE_ENV || 'development',
    PORT: process.env.PORT || 3000,
    API_VERSION: process.env.API_VERSION || 'v1',
    MONGODB_URI: process.env.MONGODB_URI || 'mongodb://localhost:27017/hikaweb',
    REDIS_URL: process.env.REDIS_URL || 'redis://localhost:6379',
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
    JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '24h',
    JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN || '7d',
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    KAVENEGAR_API_KEY: process.env.KAVENEGAR_API_KEY,
    KAVENEGAR_SENDER: process.env.KAVENEGAR_SENDER,
    TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
    ARVAN_DRIVE_ACCESS_KEY: process.env.ARVAN_DRIVE_ACCESS_KEY,
    ARVAN_DRIVE_SECRET_KEY: process.env.ARVAN_DRIVE_SECRET_KEY,
    ARVAN_DRIVE_BUCKET: process.env.ARVAN_DRIVE_BUCKET,
    ARVAN_DRIVE_REGION: process.env.ARVAN_DRIVE_REGION || 'ir-thr-at1',
    BCRYPT_SALT_ROUNDS: parseInt(process.env.BCRYPT_SALT_ROUNDS) || 12,
    RATE_LIMIT_WINDOW_MS: parseInt(process.env.RATE_LIMIT_WINDOW_MS) || 900000,
    RATE_LIMIT_MAX_REQUESTS: parseInt(process.env.RATE_LIMIT_MAX_REQUESTS) || 100,
    MAX_FILE_SIZE: parseInt(process.env.MAX_FILE_SIZE) || 10485760
  };